### ISSUE TITLE
Buttons on HomePage don't work.

### ISSUE THREAD

**Issue by MetaHumanREAL** [MetaHumanREAL/TribalsClient#3]
These three buttons here don't work, can you fix it so they will open the link in a new electron window.

- Customize this electron window so it looks like it's apart of the game. You should not be able to drag, minimize, or fullscreen it. 
- Make it so when you click out of it, back to the game, it closes automatically. (Make sure you can click inside of it thought)
<img width="68" alt="Screenshot 2023-07-24 at 12 50 16 PM" src="https://github.com/OnRushStudio/Tribals-Client/assets/45214151/79379ebb-3c9b-49da-874e-bcbd599447b2">

**Comment by Capta1nCool** [comment]
![image](https://github.com/OnRushStudio/Tribals-Client/assets/69457423/e6a29890-c0f7-4fe2-bf0c-703e014795ad)
👍🏻

**Comment by MetaHumanREAL** [comment]
Hey man, it's not exactly right.

`Make it so when you click out of it, back to the game, it closes automatically.`

When I click out of it, it goes back to tribals. But it doesn't close the window.

**Comment by Capta1nCool** [comment]
should be fixed now
