### ISSUE TITLE
Join Link button improvement.

### ISSUE THREAD

**Issue by MetaHumanREAL** [MetaHumanREAL/TribalsClient#4]
Change the Join Link button so instead of loading the link that is copied to your clipboard, it opens up a small electron window that requests a link to be pasted. Inside of the input box, make it so only Tribals.io links can be pasted in or typed in.

- Users should not be able to drag, minimize, or fullscreen this window.
- Make it so if you click to the main window, this window closes.

**Comment by Capta1nCool** [comment]
![image](https://github.com/OnRushStudio/Tribals-Client/assets/69457423/d531d844-beb5-4ee1-8147-767e0a2db39f)
